# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b23ae5fd711880efeb3fe10c07164a5"
name = "app-sandbox-extension"
handle = "app-sandbox-extension"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "daymarker-app-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
